/**
 * AppsFlyer SDK integration
 * AppsFlyer attribution and event reporting.
 * 
 * ROI360 Purchase Connector:
 *  - Purchase events are auto-generated by the connector — do NOT send manual af_purchase / af_revenue events
 *  - Sandbox = true for testing, set false for production
 */
import { Platform } from 'react-native';

let appsFlyer: any = null;
let purchaseConnector: any = null;
let purchaseConnectorConfig: any = null;
let isInitialized = false;
const pendingEvents: Array<{ name: string; values: Record<string, string> }> = [];
const pendingAdRevenueEvents: Array<{
  revenue: number;
  monetizationNetwork: string;
  adUnitId?: string;
  adType?: string;
  currency: string;
}> = [];

const APPSFLYER_DEV_KEY = 'QoZKsoqC9Me6c6azF9VqjH';

function flushPendingEvents(): void {
  if (!appsFlyer || !isInitialized) return;
  while (pendingEvents.length > 0) {
    const event = pendingEvents.shift();
    if (!event) continue;
    appsFlyer.logEvent(event.name, event.values);
  }
  while (pendingAdRevenueEvents.length > 0) {
    const event = pendingAdRevenueEvents.shift();
    if (!event) continue;
    afLogAdRevenue(
      event.revenue,
      event.monetizationNetwork,
      event.adUnitId,
      event.adType,
      event.currency,
    );
  }
}

export async function initAppsFlyer(): Promise<void> {
  if (Platform.OS === 'web') return;
  try {
    const mod = require('react-native-appsflyer');
    appsFlyer = mod.default ?? mod;

    // Purchase Connector classes
    purchaseConnector = mod.AppsFlyerPurchaseConnector ?? null;
    purchaseConnectorConfig = mod.AppsFlyerPurchaseConnectorConfig ?? null;

    // Register conversion data listener BEFORE initSdk
    appsFlyer.onInstallConversionData((data: any) => {
      const status = data?.data?.af_status;
      console.log('[AppsFlyer] Conversion data:', JSON.stringify(data?.data));
      if (status === 'Non-organic') {
        const media = data?.data?.media_source ?? 'unknown';
        const campaign = data?.data?.campaign ?? '';
        console.log('[AppsFlyer] Non-organic install from:', media, campaign);
      }
    });

    appsFlyer.onDeepLink((deepLinkData: any) => {
      console.log('[AppsFlyer] Deep link:', JSON.stringify(deepLinkData));
    });

    appsFlyer.initSdk(
      {
        devKey: APPSFLYER_DEV_KEY,
        isDebug: false,
        appId: '', // iOS App Store ID — set when published
        onInstallConversionDataListener: true,
        onDeepLinkListener: true,
        timeToWaitForATTUserAuthorization: 10,
      },
      (result: any) => {
        console.log('[AppsFlyer] Init OK', result);
        isInitialized = true;
        flushPendingEvents();
        // Initialize Purchase Connector AFTER SDK is ready
        initPurchaseConnector();
      },
      (error: any) => {
        console.error('[AppsFlyer] Init error', error);
      }
    );
  } catch (e) {
    console.error('[AppsFlyer] Not available:', e);
  }
}

// ─── ROI360 Purchase Connector ───

function initPurchaseConnector(): void {
  try {
    if (!purchaseConnector || !purchaseConnectorConfig) {
      if (__DEV__) console.log('[AppsFlyer] Purchase Connector not available in this build');
      return;
    }

    // Configure the connector
    const config = purchaseConnectorConfig.setConfig({
      logSubscriptions: true,
      logInApps: true,
      sandbox: false,
    });

    // Create connector with config
    purchaseConnector.create(config);

    // Register validation listeners (optional, for debugging)
    if (purchaseConnector.onInAppValidationResultSuccess) {
      purchaseConnector.onInAppValidationResultSuccess((result: any) => {
        console.log('[AppsFlyer] IAP validation success:', JSON.stringify(result));
      });
    }
    if (purchaseConnector.onInAppValidationResultFailure) {
      purchaseConnector.onInAppValidationResultFailure((error: any) => {
        console.error('[AppsFlyer] IAP validation error:', JSON.stringify(error));
      });
    }
    if (purchaseConnector.onSubscriptionValidationResultSuccess) {
      purchaseConnector.onSubscriptionValidationResultSuccess((result: any) => {
        console.log('[AppsFlyer] Sub validation success:', JSON.stringify(result));
      });
    }
    if (purchaseConnector.onSubscriptionValidationResultFailure) {
      purchaseConnector.onSubscriptionValidationResultFailure((error: any) => {
        console.error('[AppsFlyer] Sub validation error:', JSON.stringify(error));
      });
    }

    // Start observing transactions — auto-logs IAP & subscription events for ROI360
    purchaseConnector.startObservingTransactions();

    console.log('[AppsFlyer] Purchase Connector initialized');
  } catch (e) {
    console.error('[AppsFlyer] Purchase Connector init error:', e);
  }
}

// ─── In-App Events (non-revenue) ───

export function afLogEvent(eventName: string, eventValues: Record<string, string> = {}): void {
  if (!appsFlyer || Platform.OS === 'web') return;
  // IMPORTANT: Do NOT send af_purchase / af_revenue events manually — ROI360 connector handles them
  if (eventName === 'af_purchase') {
    if (__DEV__) console.log('[AppsFlyer] Skipping manual af_purchase — handled by Purchase Connector');
    return;
  }
  if (!isInitialized) {
    pendingEvents.push({ name: eventName, values: eventValues });
    return;
  }
  try {
    appsFlyer.logEvent(eventName, eventValues);
    if (__DEV__) console.log('[AppsFlyer] Event:', eventName, eventValues);
  } catch (e) {
    if (__DEV__) console.warn('[AppsFlyer] logEvent error:', e);
  }
}

/**
 * @deprecated — Do NOT use. ROI360 Purchase Connector auto-generates purchase events.
 * Kept as no-op so existing call sites don't crash.
 */
export function afLogPurchase(_revenue: number, _currency: string, _productId: string): void {
  if (__DEV__) console.log('[AppsFlyer] afLogPurchase is no-op — Purchase Connector handles revenue');
}

/**
 * Log impression-level ad revenue via AppsFlyer ROI360 logAdRevenue API.
 * This generates af_ad_revenue events with proper attribution for ROI360 postbacks.
 */
export function afLogAdRevenue(
  revenue: number,
  monetizationNetwork: string,
  adUnitId?: string,
  adType?: string,
  currency: string = 'USD',
): void {
  if (Platform.OS === 'web' || revenue <= 0) return;
  if (!appsFlyer || !isInitialized) {
    pendingAdRevenueEvents.push({
      revenue,
      monetizationNetwork,
      adUnitId,
      adType,
      currency,
    });
    return;
  }
  try {
    // Import MEDIATION_NETWORK enum
    const mod = require('react-native-appsflyer');
    const MEDIATION_NETWORK = mod.MEDIATION_NETWORK;

    const adRevenueData = {
      monetizationNetwork: monetizationNetwork,
      mediationNetwork: MEDIATION_NETWORK?.APPLOVIN_MAX ?? 1,
      currencyIso4217Code: currency,
      revenue: revenue,
      additionalParameters: {
        ad_unit: adUnitId ?? '',
        ad_type: adType ?? '',
      },
    };

    appsFlyer.logAdRevenue(adRevenueData);
    if (__DEV__) console.log('[AppsFlyer] logAdRevenue:', JSON.stringify(adRevenueData));
  } catch (e) {
    if (__DEV__) console.warn('[AppsFlyer] logAdRevenue error:', e);
  }
}

export function afLogLevelUp(level: string): void {
  afLogEvent('af_level_achieved', { af_level: level });
}

export function afLogTutorialComplete(): void {
  afLogEvent('af_tutorial_completion', { af_success: 'true' });
}

export function afLogContentView(contentId: string, contentType: string): void {
  afLogEvent('af_content_view', {
    af_content_id: contentId,
    af_content_type: contentType,
  });
}
